import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#7f2a21",
        "on-tertiary-container": "#76231b",
        "surface-container-high": "#2a2a2a",
        "surface-container-low": "#1c1b1b",
        "on-secondary-container": "#ffaea8",
        "surface-container-highest": "#353534",
        "on-primary-fixed": "#002109",
        "on-secondary": "#68000a",
        "inverse-primary": "#006e2f",
        "secondary-fixed-dim": "#ffb3ad",
        "surface-dim": "#131313",
        "error": "#ffb4ab",
        "surface": "#131313",
        "on-surface-variant": "#bccbb9",
        "background": "#131313",
        "tertiary-container": "#ff8b7c",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-primary": "#003915",
        "surface-variant": "#353534",
        "on-tertiary-fixed": "#410001",
        "on-primary-container": "#004b1e",
        "inverse-surface": "#e5e2e1",
        "on-error-container": "#ffdad6",
        "tertiary": "#ffb5ab",
        "on-secondary-fixed": "#410004",
        "on-secondary-fixed-variant": "#930013",
        "inverse-on-surface": "#313030",
        "primary-fixed": "#6bff8f",
        "on-background": "#e5e2e1",
        "secondary": "#ffb3ad",
        "primary-container": "#22c55e",
        "outline": "#869585",
        "on-tertiary": "#60130d",
        "tertiary-fixed-dim": "#ffb4a9",
        "on-primary-fixed-variant": "#005321",
        "on-surface": "#e5e2e1",
        "primary-fixed-dim": "#4ae176",
        "outline-variant": "#3d4a3d",
        "surface-container": "#201f1f",
        "primary": "#4be277",
        "surface-tint": "#4ae176",
        "surface-container-lowest": "#0e0e0e",
        "surface-bright": "#3a3939",
        "secondary-fixed": "#ffdad7",
        "tertiary-fixed": "#ffdad5",
        "secondary-container": "#a40217",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["var(--font-manrope)", "sans-serif"],
        body: ["var(--font-inter)", "sans-serif"],
        label: ["var(--font-inter)", "sans-serif"],
      },
    },
  },
  plugins: [],
};
export default config;
